#!/bin/bash
set -e

### BEGIN INIT INFO
# Provides:   cloudfoundry
# Required-Start: $local_fs $remote_fs $network $time
# Required-Stop:  $local_fs $remote_fs $network $time
# Should-Start:   $syslog
# Should-Stop:    $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:  CloudFoundry PaaS platform
### END INIT INFO

MONIT=/var/vcap/bosh/bin/monit

case "$1" in
  start)
    $MONIT
    sleep 5
    $MONIT start all
  ;;
  status)
    $MONIT status
  ;;
  summary)
    $MONIT summary
  ;;
  stop)
    $MONIT stop all
  ;;
esac

exit 0